---
title: "R Notebook"
output: html_notebook
---


```{r}
library(boot)
library(DAAG)
library(lme4)

library(tidyverse)
library(caret)


library(plyr)
library(caret)
library(car)
library(pROC)
library(readxl)
library(pROC)
library(readxl)
library(glmnet)
library(glmnetUtils)

library(optimx)
library(arrow)
```


```{r}
testtest <- commandArgs()
mydata <- read_excel("./fractions2013.xlsx")
names(mydata)


Model_type=c("AFM","PFM","IFM")

Models_AIC <- rep(1,3);
Models_BIC <- rep(1,3);
ACCcv <- rep(1,3);
NumParameters <- rep(1,3);
Likelihood <- rep(1,3);
BrierScore <- rep(1,3);
LogLoss <- rep(1,3);
names(LogLoss)<- c("AFM","PFM","IFM")
names(Models_AIC)<-c("AFM", "PFM", "IFM")
names(Models_BIC)<-c("AFM", "PFM", "IFM")
names(ACCcv)<-c("AFM", "PFM", "IFM")
names(NumParameters)<-c("AFM", "PFM", "IFM")
names(Likelihood)<-c("AFM", "PFM", "IFM")
names(BrierScore)=c("AFM","PFM","IFM")


AICc <- rep(1,3);
names(AICc) <- c("AFM","PFM","IFM")

RMSE <- rep(1,3);
names(RMSE)<-c("AFM","PFM","IFM")

```



```{r}
## Prepare Data

mydata$`First Attempt` = revalue(mydata$`First Attempt`, c("incorrect"= 0))
mydata$`First Attempt` = revalue(mydata$`First Attempt`, c("hint"= 0))
mydata$`First Attempt` = revalue(mydata$`First Attempt`, c("correct"= 1))
  
mydata["Outcome"] = as.numeric(mydata$`First Attempt`)

mydata <- na.omit(mydata)
  
```


```{r}


mydata["KCModel"] = mydata$`KC (Default)`
mydata["OpportunityModel"] = as.numeric(as.character(mydata$`Opportunity`))
  

mydata["CorrectModel"] = as.numeric(as.character(mydata$`Corrects`))
mydata["IncorrectModel"] = as.numeric(as.character(mydata$`Incorrects`))

mydata["TellsModel"] = as.numeric(as.character(mydata$`Hints`))
  
```



```{r}

AFM_form <- Outcome ~ AnonStudentId +KCModel + KCModel:OpportunityModel
AFMTrainingModel <- glm(AFM_form, family=binomial(), data= mydata); 


PFM_form <- Outcome ~ AnonStudentId +KCModel + KCModel:(CorrectModel + IncorrectModel)
PFMTrainingModel <- glm(PFM_form, family=binomial(), data= mydata); 


IFM_form <- Outcome ~ AnonStudentId +KCModel + KCModel:(CorrectModel + IncorrectModel + TellsModel)
IFMTrainingModel <- glm(IFM_form, family=binomial(), data= mydata); 

```


```{r}
####################################
# Create training and testing using Pareto Principle
# 
# cols = ncol(mydata)
# sample_size = floor(0.8 *nrow(mydata))
# set.seed(123)
#   
# train_ind <- sample(seq_len(nrow(mydata)), size = sample_size)
# traindata <- mydata[train_ind, ]
# testdata <- mydata[-train_ind, ]
# 
# 
# AFMTrainingTestModel <- glm(AFM_form, family=binomial(), data= traindata); 
# 
# PFMTrainingTestModel <- glm(PFM_form, family=binomial(), data= traindata); 
# 
# IFMTrainingTestModel <- glm(IFM_form, family=binomial(), data= traindata); 
# 
# 
# afmprobabilities <- AFMTrainingTestModel %>% predict(testdata, type = "response")
# afmpredicted_value <- ifelse(afmprobabilities >0.5,1,0)  
# afmconfusion_mat = as.matrix(table(Actual_Values = testdata$Outcome, Predicted_Values = afmpredicted_value)) 
# 
# pfmprobabilities <- PFMTrainingTestModel %>% predict(testdata, type = "response")
# pfmpredicted_value <- ifelse(pfmprobabilities >0.5,1,0)  
# pfmconfusion_mat = as.matrix(table(Actual_Values = testdata$Outcome, Predicted_Values = pfmpredicted_value)) 
# 
# ifmprobabilities <- IFMTrainingTestModel %>% predict(testdata, type = "response")
# ifmpredicted_value <- ifelse(ifmprobabilities >0.5,1,0)  
# ifmconfusion_mat = as.matrix(table(Actual_Values = testdata$Outcome, Predicted_Values = ifmpredicted_value)) 
```


```{r}
####################################
# Here are the 10-fold cross validiation for the models.
#####################################
  

cvafm = CVbinary(AFMTrainingModel);
ACCcv["AFM"] <- cvafm$acc.cv


cvpfm = CVbinary(PFMTrainingModel);
ACCcv["PFM"] <- cvpfm$acc.cv

cvifm = CVbinary(IFMTrainingModel);
ACCcv["IFM"] <- cvifm$acc.cv


```


```{r}
# Create training and testing using Pareto Principle

cols = ncol(mydata)
sample_size = floor(0.8 *nrow(mydata))
set.seed(123)
   
train_ind <- sample(seq_len(nrow(mydata)), size = sample_size)
traindata <- mydata[train_ind, ]
testdata <- mydata[-train_ind, ]

AFMTrainingTestModel <- glm(AFM_form, family=binomial(), data= traindata); 
PFMTrainingTestModel <- glm(PFM_form, family=binomial(), data= traindata); 
IFMTrainingTestModel <- glm(IFM_form, family=binomial(), data= traindata); 

afmProbabilities <- AFMTrainingTestModel %>% predict(testdata, type = "response")

testdata$afmprediction <- ifelse(afmProbabilities >0.5,1,0)

#Check the error between real outcomes and predicted variables 
RMSE["AFM"]<-sqrt(mean((testdata$Outcome - testdata$afmprediction)^2))



pfmProbabilities <- PFMTrainingTestModel %>% predict(testdata, type = "response")


testdata$pfmprediction <- ifelse(pfmProbabilities >0.5,1,0)

#Check the error between real outcomes and predicted variables 
RMSE["PFM"]<-sqrt(mean((testdata$Outcome - testdata$pfmprediction)^2))



ifmProbabilities <- IFMTrainingTestModel %>% predict(testdata, type = "response")

testdata$ifmprediction <- ifelse(ifmProbabilities >0.5,1,0)

#Check the error between real outcomes and predicted variables 
RMSE["IFM"]<-sqrt(mean((testdata$Outcome - testdata$ifmprediction)^2))

confusion_matrix=table(ACTUAL=testdata$Outcome,PREDICTED=testdata$ifmprediction)
TN=confusion_matrix[1,1]
FP=confusion_matrix[1,2]
FN=confusion_matrix[2,1]
TP=confusion_matrix[2,2]
Precision=TP/ (TP+FP)
Recall= TP/ (TP+FN)
F1 = (2*(Precision*Recall)) / (Precision+Recall)
```




```{r}

N<-nrow(mydata)
Models_AIC["AFM"]<-summary(AFMTrainingModel)$aic	
Models_BIC["AFM"]<-summary(AFMTrainingModel)$aic+length(coef(AFMTrainingModel))*(log(N)-2);


Models_AIC["PFM"]<-summary(PFMTrainingModel)$aic	
Models_BIC["PFM"]<-summary(PFMTrainingModel)$aic+length(coef(PFMTrainingModel))*(log(N)-2);

Models_AIC["IFM"]<-summary(IFMTrainingModel)$aic	
Models_BIC["IFM"]<-summary(IFMTrainingModel)$aic+length(coef(IFMTrainingModel))*(log(N)-2);


NumParameters["AFM"] <- length(coef(AFMTrainingModel))
NumParameters["PFM"] <- length(coef(PFMTrainingModel))
NumParameters["IFM"] <- length(coef(IFMTrainingModel))
  
Likelihood["AFM"] <- -summary(AFMTrainingModel)$deviance/2
Likelihood["PFM"] <- -summary(PFMTrainingModel)$deviance/2
Likelihood["IFM"] <- -summary(IFMTrainingModel)$deviance/2


afmpred.prob <- predict(AFMTrainingModel,type='response')
pfmpred.prob <- predict(PFMTrainingModel,type='response')
ifmpred.prob <- predict(IFMTrainingModel,type='response')

BrierScore["AFM"] <- mean((afmpred.prob-mydata$Outcome)^2)
BrierScore["PFM"] <- mean((pfmpred.prob-mydata$Outcome)^2)
BrierScore["IFM"] <- mean((ifmpred.prob-mydata$Outcome)^2)


AICc["AFM"] <- -2*(Likelihood["AFM"])+2*NumParameters["AFM"]+(2*NumParameters["AFM"]*(NumParameters["AFM"]+1)/(N-NumParameters["AFM"]-1))

AICc["PFM"] <- -2*(Likelihood["PFM"])+2*NumParameters["PFM"]+(2*NumParameters["PFM"]*(NumParameters["PFM"]+1)/(N-NumParameters["PFM"]-1))


AICc["IFM"] <- -2*(Likelihood["IFM"])+2*NumParameters["IFM"]+(2*NumParameters["IFM"]*(NumParameters["IFM"]+1)/(N-NumParameters["IFM"]-1))




logLoss <- function(pred, actual){
  -mean(actual * log(pred) + (1 - actual) * log(1 - pred))}




LogLoss["AFM"] <- logLoss(pred = afmpred.prob,actual = mydata$Outcome)
LogLoss["PFM"] <- logLoss(pred = pfmpred.prob,actual = mydata$Outcome)
LogLoss["IFM"] <- logLoss(pred = ifmpred.prob,actual = mydata$Outcome)



print(Models_AIC)
print(Models_BIC)
print(NumParameters)
print(Likelihood)
print(BrierScore)
print(LogLoss)


```
```{r}

exportdf <- cbind(Model_type,Models_AIC,AICc,Models_BIC,NumParameters,Likelihood,BrierScore,LogLoss,RMSE,ACCcv)


write.csv(exportdf, "./R_results.csv", row.names=FALSE)
```

```{r}
summary(AFMTrainingModel)
summary(PFMTrainingModel)
summary(IFMTrainingModel)
```

```{r}

#Not working rn


####################################################################################################
  ####################################################################################################
  # Then we run leave-one-student-at-one-time cross validation by using lmer 
  # on all models
  # The output of average RMSE is stored
  ####################################################################################################
  ####################################################################################################

# 
# 
#   
#   students <-unique(mydata$`AnonStudentId`)
# length(students)
#   testing = students[1:(length(students)%/%3)]
#   testing
#   tester = subset(mydata,mydata$`AnonStudentId` %in% testing)
#   
#   students <-unique(tester$AnonStudentId)
#   #lmerAFM_RMSE=rep(1,length(students));
#   #lmerAFMLT_RMSE=rep(1,length(students));
#   #lmerAFMQT_RMSE=rep(1,length(students));
#   lmerAFM_RMSE=rep(1,length(tester));
#   lmerPFM_RMSE=rep(1,length(tester));
#   lmerIFM_RMSE=rep(1,length(tester));
#   
#   
#   i=1
#   print(length(students))
#   
#  
#   for (stu in students){
#     stu = students[i]
#     print(i)
#     print(stu)
#     TrainingDataTemp  <- subset(tester, AnonStudentId != stu);
#     TestingDataTemp  <- subset(tester, AnonStudentId == stu);
#     #for AFM
#     tryCatch({
#       afmlmer <- glmer(Outcome ~ (1|AnonStudentId) + KCModel + KCModel:OpportunityModel, data=TrainingDataTemp, family=binomial(), control = glmerControl(optimizer = "optimx", calc.derivs = FALSE,optCtrl = list(method = "nlminb", starttests = FALSE, kkt = FALSE)))  
#       lmerAFM_mm = model.matrix(terms(afmlmer),TestingDataTemp);
#       tryCatch({
#         TestingDataTemp$Correct_lmerAFMPredict = 1/(1+ exp(-(lmerAFM_mm %*% fixef(afmlmer))))
#         lmerAFM_RMSE[i] = sqrt(mean((TestingDataTemp$Outcome - TestingDataTemp$Correct_lmerAFMPredict)^2))
#         print(lmerAFM_RMSE[i])
#         
#       }, 
#       lmerAFM_RMSE[i] <- NA,
#       error = function(e){cat("AFM ERROR :",conditionMessage(e), "\n")})
#     }, 
#     lmerAFM_RMSE[i] <- NA,
#     error = function(e){cat("AFM ERROR :",conditionMessage(e), "\n")})
#     
#   
#     
#     #for PFM
#      tryCatch({
#        pfmlmer <- glmer(Outcome ~ (1|AnonStudentId) + KCModel + KCModel:(CorrectModel+IncorrectModel), data=TrainingDataTemp, family=binomial(logit))  
#        lmerPFM_mm = model.matrix(terms(pfmlmer),TestingDataTemp);
#        tryCatch({
#          TestingDataTemp$Correct_lmerPFMPredict = 1/(1+ exp(-(lmerPFM_mm %*% fixef(pfmlmer))))
#          lmerPFM_RMSE[i] = sqrt(mean((TestingDataTemp$Outcome - TestingDataTemp$Correct_lmerPFMPredict)^2))
#          print("PFM")
#          print(lmerPFM_RMSE[i])
#        }, 
#        lmerPFM_RMSE[i] <- NA,
#        error = function(e){cat("PFM ERROR :",conditionMessage(e), "\n")})
#      }, 
#      lmerPFM_RMSE[i] <- NA,
#      error = function(e){cat("PFM ERROR :",conditionMessage(e), "\n")})
#    
#    
#    tryCatch({
#        ifmlmer <- glmer(Outcome ~ (1|AnonStudentId) + KCModel + KCModel:(CorrectModel+IncorrectModel+TellsModel), data=TrainingDataTemp, family=binomial(logit))
#        lmerIFM_mm = model.matrix(terms(ifmlmer),TestingDataTemp);
#        tryCatch({
#          TestingDataTemp$Correct_lmerIFMPredict = 1/(1+ exp(-(lmerIFM_mm %*% fixef(ifmlmer))))
#          lmerIFM_RMSE[i] = sqrt(mean((TestingDataTemp$Outcome - TestingDataTemp$Correct_lmerIFMPredict)^2))
#          print("IFM")
#          print(lmerIFM_RMSE[i])
#        }, 
#        lmerIFM_RMSE[i] <- NA,
#        error = function(e){cat("IFM ERROR :",conditionMessage(e), "\n")})
#      }, 
#      lmerIFM_RMSE[i] <- NA,
#      error = function(e){cat("IFM ERROR :",conditionMessage(e), "\n")})}
#    
#   
#     
#   
#   lmerAFM_RMSE = na.omit(lmerAFM_RMSE)
#   lmerPFM_RMSE = na.omit(lmerPFM_RMSE)
#   lmerIFM_RMSE = na.omit(lmerIFM_RMSE)
#   RMSElmer["AFM"]=mean(lmerAFM_RMSE)
#   RMSElmer["PFM"]=mean(lmerPFM_RMSE)
#   RMSElmer["IFM"]=mean(lmerIFM_RMSE)
#   
# 
#   print(RMSElmer)
# ```
```





